version: "3.7"

x-app-config: &app-config
  DJANGO_ENV: dev
  DJANGO_SECRET_KEY: secret_key
  EMAIL_USE_SSL: 'false'
  EMAIL_USE_TLS: 'true'
  EMAIL_HOST: smtp.gmail.com
  EMAIL_PORT: 587
  DJ_SECRET_KEY: ${DJ_SECRET_KEY}
  EMAIL_HOST_USER: ${EMAIL_HOST_USER}
  EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
  DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
  NEW_RELIC_ACCOUNT_ID: ${NEW_RELIC_ACCOUNT_ID}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
  ROLLBAR_ACCESS_TOKEN: ${ROLLBAR_ACCESS_TOKEN}
  COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
  NEW_RELIC_CONFIG_FILE: newrelic.ini
  DJANGO_ENV: dev
  AWS_ACCESS_KEY_ID: ''
  AWS_SECRET_ACCESS_KEY: ''
  AWS_STORAGE_BUCKET_NAME: ''
  AWS_REGION_NAME: ''
  REDIS_HOST: redis
  REDIS_PORT: 6379

x-db-config: &db-config
  DATABASE_NAME: postgres
  DATABASE_USER: postgres
  DATABASE_PASSWORD: pgpassword
  DATABASE_HOST: db
  DATABASE_PORT: 5432
  POSTGRES_PASSWORD: pgpassword

services:
  api:
    image: userapp_api
    build:
      context: .
      target: base
    environment:
      <<: *app-config
      <<: *db-config
    depends_on:
      - db
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

  db:
    image: postgres:12.5-alpine
    environment: *db-config
    logging:
      driver: none
    ports:
      - "5432:5432"

volumes:
  sqlvolume:
