# Generated by Django 4.1.7 on 2023-03-05 05:59

from django.db import migrations, models
import task_manager.main.models.user


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("developer", "Developer"),
                    ("manager", "Manager"),
                    ("admin", "Admin"),
                ],
                default="developer",
                max_length=255,
                validators=[task_manager.main.models.user.User.validate_role_choices],
            ),
        ),
    ]
