# Generated by Django 4.1.7 on 2023-03-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tag_user_name_user_role_user_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new task', 'New'), ('in development', 'In Development'), ('in qa', 'In Qa'), ('in code review', 'In Code Review'), ('ready for release', 'Ready For Release'), ('released', 'Released'), ('archived', 'Archived')], default='new task', max_length=255),
        ),
    ]
