# Generated by Django 4.1.7 on 2023-03-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_user_name_alter_user_surname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="surname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
