# Generated by Django 4.1.7 on 2023-03-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_user_date_of_birth_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
