# Generated by Django 4.1.7 on 2023-03-14 08:16

from django.db import migrations, models
import task_manager.main.services.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_user_avatar_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=task_manager.main.services.storage_backends.public_storage,
                upload_to="",
            ),
        ),
    ]
