name: Main

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        env:
          COVERAGE: true
          RAILS_ENV: test
          DJ_SECRET_KEY: ${DJ_SECRET_KEY}
          EMAIL_HOST_USER: ${EMAIL_HOST_USER}
          EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
          DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
          NEW_RELIC_ACCOUNT_ID: ${NEW_RELIC_ACCOUNT_ID}
          NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
          ROLLBAR_ACCESS_TOKEN: ${ROLLBAR_ACCESS_TOKEN}
        run: docker-compose --file docker-compose.ci.yml run --rm api make test
      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: Run tests

  coveralls_finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true